---
output: github_document
---

<!-- readme.md is generated by readme.rmd, please edit that document instead -->

# theme61

```{r echo = FALSE, message = FALSE, warning = FALSE}
devtools::load_all()
library(theme61)
library(ggplot2)
library(lubridate)
library(data.table)

knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-"
)
```

This package helps you create graphs that follow the e61 Institute graphing style. It provides functions that make it easier to make aesthetic graphs and easy access to the Institute's colour palette.

### Installing theme61

If you haven't already, install the `remotes` package:

`install.packages("remotes")`

Then install from GitHub:

`remotes::install_github("e61-institute/theme61", upgrade = "always")`

theme61 works out of the box with the packages this installs. A few optional
features need one extra package each, which you can install if and when you
want them: `magick` for `add_e61_logo()`, `ggmap` and `sf` for the map
functions, and `remotes` itself for the in-session update prompt.

Then load into R:

`library(theme61)`

### Using theme61

The [package website](https://e61-institute.github.io/theme61/) contains a lot of information on how to use theme61.

Start by reading the [Get started](articles/theme61.html) article.

There is also a wealth of information contained in the individual [function documentation](reference/index.html) that answers common usage questions.
