#' Add On-graph Labels to Graphs
#'
#' Wrapper function around \code{annotate()} that helps you add labels for
#' lines, columns or other elements directly onto the graph plot as a
#' replacement for legends outside the plot area.
#'
#' Automatically chooses the correct colour in the theme61 colour palette if you
#' provide the total number of labels, and the relative ordering of each label.
#'
#' @param label String. Label text to be displayed.
#' @param x Numeric or string. X-axis position of the label text.
#' @param y Numeric or string. Y-axis position of the label text.
#' @param n_labs Integer. Total number of labels on the graph.
#' @param n Integer. Indicate which (*n*th) element this label corresponds to.
#' @param colour String. Manually specify the colour of the label text.
#'   Overrides the colours generated by \code{n_labs} and \code{n}.
#' @param size Integer. Size of the text, the default size should be appropriate
#'   in most cases.
#'
#' @return ggplot2 object
#' @export
plot_label <- function(label, x, y, n_labs = NULL, n = NULL, colour = NULL, size = 3) {

  if (is.null(colour) && (is.null(n_labs) || is.null(n)))
    stop("If 'colour' is not provided then you must specify values for 'n_labs' and 'n'.")

  if (is.null(colour)) colour <- e61_palette(n_labs)[[n]]

  # Automatically convert dates to dates if specified, so the user doesn't have
  # to wrap dates in as.Date() which saves some room.
  if (class(try(as.Date(x), silent = TRUE)) != "try-error") {
    x <- as.Date(x)
  }

  annotate("text", label = label, x = x, y = y, size = size,
           colour = colour)

}

#' Add Multiple On-graph Labels to Graphs
#'
#' This is a vectorised version of \code{plot_label} to allow you to easily add
#' multiple plot labels onto graphs.
#' @param label String vector. Label text to be displayed.
#' @param x Numeric or string vector. X-axis positions of the label text.
#' @param y Numeric or string vector. Y-axis positions of the label text.
#' @param colour String vector. Manually specify the colours of the label text.
#' @param size Integer. Size of the text, the default size should be appropriate
#'   in most cases.
#'
#' @return ggplot2 object
#' @export
mplot_label <- function(label, x, y, colour = NULL, size = 3) {

  if (!all.equal(length(label), length(x), length(y)))
    stop("The number of x and y positions must equal the number of labels.")

  if (!is.null(colour)) {
    if (length(colour) != length(label)) stop("The number of colours must equal the number of labels.")
  } else {
    colour <- label
  }

  plot_lab <- data.table(
    lab = label,
    x = x,
    y = y,
    colour = colour
  )

  gg <-
    geom_text(data = plot_lab, aes(x, y, label = lab, colour = colour), size = 3)

  return(gg)

}
