#' Add On-graph Labels to Graphs
#'
#' Wrapper function around \code{annotate()} that helps you add labels for
#' lines, columns or other elements directly onto the graph plot as a
#' replacement for legends outside the plot area.
#'
#' Automatically chooses the correct colour in the theme61 colour palette if you
#' provide the total number of labels, and the relative ordering of each label.
#'
#' @param label String. Label text to be displayed.
#' @param x Numeric or string. X-axis position of the label text.
#' @param y Numeric or string. Y-axis position of the label text.
#' @param n_labs Integer. Total number of labels on the graph.
#' @param n Integer. Indicate which \emph{n}th element this label corresponds
#'   to.
#' @param colour String. Manually specify the colour of the label text.
#'   Overrides the colours generated by \code{n_labs} and \code{n}.
#' @param size Integer. Size of the text, the default size should be appropriate
#'   in most cases.
#' @param hjust A numeric value from 0-1. Adjusts the alignment of the text. 0
#'   left-aligns (default), 0.5 centre-aligns and 1 right-aligns.
#' @param geom String. Either "text" (default) or "label". "label" adds a white
#'   box around the text which could be useful sometimes.
#'
#' @return ggplot2 object
#' @export
plot_label <-
  function(label,
           x,
           y,
           n_labs = NA,
           n = NA,
           colour = NA,
           size = 3.5,
           hjust = 0,
           geom = c("text", "label")) {
    geom <- match.arg(geom)

    if (is.na(colour) && (is.na(n_labs) || is.na(n)))
      stop("If 'colour' is not provided then you must specify values for 'n_labs' and 'n'.")

    if (is.na(colour)) colour <- e61_palette(n_labs)[[n]]

    # # Automatically convert dates to dates if specified, so the user doesn't have
    # # to wrap dates in as.Date() which saves some room.
    # if (class(try(as.Date(x), silent = TRUE)) != "try-error") {
    #   x <- as.Date(x)
    # }

    annotate(geom = geom, label = label, x = x, y = y, size = size, colour = colour, hjust = hjust)

  }

#' Add multiple on-graph labels to graphs
#'
#' This is a vectorised version of \code{plot_label} to allow you to easily add
#' multiple plot labels onto graphs.
#' @param label String vector. Label text to be displayed.
#' @param x Numeric or string vector. X-axis positions of the label text.
#' @param y Numeric or string vector. Y-axis positions of the label text.
#' @param colour Optional vector of manually-selected colours. Default uses the
#'   order of colours in the e61 palette.
#' @param size Integer. Size of the text, the default size should be appropriate
#'   in most cases.
#' @param hjust A numeric value from 0-1. Adjusts the alignment of the text. 0
#'   left-aligns (default), 0.5 centre-aligns and 1 right-aligns.
#' @param geom String. Either "text" (default) or "label". "label" adds a white
#'   box around the text which could be useful sometimes.
#'
#' @return ggplot2 object
#' @export
mplot_label <-
  function(label,
           x,
           y,
           colour = NA,
           size = 3.5,
           hjust = 0,
           geom = c("text", "label")) {

    geom <- match.arg(geom)

    if (!all.equal(length(label), length(x), length(y)))
      stop("The number of x and y positions must equal the number of labels.")

    # df requires vectors to be equal lengths
    if (length(colour) == 1 && is.na(colour)) {
      colour <- rep(colour, length(label))
    } else if (length(colour) != length(label)) {
      stop("The number of colours must equal the number of labels.")
    }

    plot_lab <- data.frame(
      label = label,
      x = x,
      y = y,
      colour = colour,
      size = rep(size, length(label)),
      hjust = rep(hjust, length(label)),
      geom = rep(geom, length(label))
    )

    plot_lab$n_labs <- nrow(plot_lab)
    plot_lab$n <- 1:nrow(plot_lab)

    # This converts the data.frame into a list of lists, where the 1st level list
    # corresponds to each label, and the elements of the 2nd level list are the
    # components needed for plot_label()
    plot_lab <- split(plot_lab, seq(nrow(plot_lab)))
    plot_lab <- lapply(plot_lab, as.list)

    # Runs through each list element and calls plot_label() to generate the labels
    retval <-
      lapply(plot_lab, function(x) {
        plot_label(
          label = x$label,
          x = x$x,
          y = x$y,
          n_labs = x$n_labs,
          n = x$n,
          colour = x$colour,
          size = x$size,
          hjust = x$hjust,
          geom = x$geom
        )
      })

    return(retval)

}
